"""empty message

Revision ID: 01fd1e55d53b
Revises: 2d6392ee92d8
Create Date: 2023-08-20 22:55:49.151762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01fd1e55d53b'
down_revision = '2d6392ee92d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('questions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['subject_name'], ['name'])
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', mysql.VARCHAR(length=126), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_2', 'subject', ['subject_id'], ['id'])
        batch_op.drop_column('subject_name')

    # ### end Alembic commands ###
