"""empty message

Revision ID: 2d6392ee92d8
Revises: eaa41db48e6a
Create Date: 2023-08-20 08:16:48.382482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d6392ee92d8'
down_revision = 'eaa41db48e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('questions_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'year', ['year_'], ['name'])
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_3', 'year', ['year'], ['name'])
        batch_op.drop_column('year_')

    # ### end Alembic commands ###
