"""empty message

Revision ID: cc43dd2ced2a
Revises: 465ee18e2e63
Create Date: 2023-09-01 17:55:10.142225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc43dd2ced2a'
down_revision = '465ee18e2e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_record', schema=None) as batch_op:
        batch_op.drop_column('overall')

    # ### end Alembic commands ###
