"""empty message

Revision ID: eaa41db48e6a
Revises: 
Create Date: 2023-08-19 23:01:38.676372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa41db48e6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_term', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('subject',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_term', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('year',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_term', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('questions',
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('admin_id', sa.String(length=126), nullable=True),
    sa.Column('subject_id', sa.String(length=126), nullable=True),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_term', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['year'], ['year.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('question')
    )
    op.create_table('student',
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('year_', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_term', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['year_'], ['year.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('student_subject',
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_name'], ['student.email'], ),
    sa.ForeignKeyConstraint(['subject_name'], ['subject.name'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_subject')
    op.drop_table('student')
    op.drop_table('questions')
    op.drop_table('year')
    op.drop_table('subject')
    op.drop_table('admin')
    # ### end Alembic commands ###
